title: Javier Encinas
description: Another personal website.
lsi: false
safe: true
source: jencinas
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
